<a href="https://colab.research.google.com/github/alex-scaria/Pandas/blob/master/iphuman.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, Activation, Conv2D, MaxPool2D, Flatten
from keras.optimizers import SGD
from keras.layers.convolutional import Conv2D
from keras.layers import Conv2D, MaxPooling2D, Embedding, Reshape, Concatenate, Dropout
from keras.layers import ZeroPadding2D


In [0]:
model = Sequential()

In [0]:
model.add(Conv2D(300, kernel_size=(3, 3), activation='relu', input_shape=(32,32,1),padding='same'))

In [0]:
#keras.layers.ZeroPadding2D(padding=(1,1))

In [0]:
model.add(MaxPooling2D(pool_size=(2, 2)))


In [0]:
model.add(Conv2D(250, (3, 3), activation='relu', padding='same'))


In [0]:
#ZeroPadding2D(padding=(1,1))

In [0]:
model.add(MaxPooling2D(pool_size=(2, 2)))


In [0]:
model.add(Conv2D(200, kernel_size=(3, 3), activation='relu', padding='same'))


In [0]:
#ZeroPadding2D(padding=(1,1))

In [0]:
model.add(Conv2D(150, kernel_size=(3, 3), activation='relu', padding='same'))


In [0]:
#ZeroPadding2D(padding=(1,1))

In [0]:
model.add(Conv2D(100, kernel_size=(3, 3), activation='relu',padding='same'))


In [0]:
#ZeroPadding2D(padding=(1,1))

In [0]:
model.add(Flatten())


In [0]:
model.add(Dense(500, activation='relu'))

In [0]:
from keras import losses
from keras import optimizers
sgd = optimizers.SGD(lr=0.0003)

model.compile(loss=losses.mean_squared_error, optimizer=sgd, metrics=['accuracy'])


In [0]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/My Drive/colab_data/training_human_32x32.csv')

In [0]:
df.head()



left_eye_center_x  left_eye_center_y  right_eye_center_x  \
0                 21                 10                   1   
1                 23                 11                   9   
2                 21                 12                  10   
3                 21                 12                  10   
4                 19                  6                   5   

   right_eye_center_y  nose_tip_x  nose_tip_y  \
0                  12          12          22   
1                  11          15          22   
2                  13          15          18   
3                  20          19          22   
4                  18          17          21   

                                               image  \
0  102 104 106 109 112 114 116 116 114 118 118 11...   
1  29 11 2 13 35 50 59 63 63 66 71 76 80 83 84 84...   
2  34 31 26 19 17 18 18 17 32 45 58 61 54 50 54 6...   
3  0 0 0 2 4 0 0 0 7 0 0 8 37 59 70 74 77 83 84 7...   
4  131 138 147 155 160 163 164 165 161 179 165 15...   

                                            image_gt  
0  0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0....  
1  0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0....  
2  0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0....  
3  0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0....  
4  0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0....

In [0]:
df.columns


Index(['left_eye_center_x', 'left_eye_center_y', 'right_eye_center_x',
       'right_eye_center_y', 'nose_tip_x', 'nose_tip_y', 'image', 'image_gt'],
      dtype='object')

In [0]:
y.shape

(8560, 3, 2)

In [0]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/My Drive/colab_data/training_human_32x32.csv')

In [0]:
dataList = []
for index, row in df.iterrows(): 
    mylist = [row.left_eye_center_x, row.left_eye_center_y]
    mylist1 = [row.right_eye_center_x, row.right_eye_center_y]
    mylist2 = [row.nose_tip_x, row.nose_tip_y]
    dataList.append(mylist)
    dataList.append(mylist1)
    dataList.append(mylist2)


In [0]:
i=0
new_list=[]
while i<len(dataList):
  new_list.append(np.array(dataList[i:i+3]).flatten())
  i+=3

y = np.array(new_list)
print(y.shape)
y_test=y[0:1713]
y_train=y[1713:]
print(y_test.shape)
print(y_train.shape)


(8560, 6)
(1713, 6)
(6847, 6)


In [0]:
#my__list = df['image'].tolist()

#matrix = []
#for i in my__list:
    #image_rows = []

  #    print(i)    
#one_row = my__list[0]
   
  #mylist  = i.split()
   # while mylist != []:
#image_rows.append([float(Val) for Val in mylist[:32]])
      #    mylist = mylist[32:]
   # matrix.append(image_rows)


#X = np.array(matrix)
#type(X)
#print(X)
print(y_train)


[  4 255  15 ...  12  20  17]


In [0]:
from keras.preprocessing import image

In [0]:
X_test = []

for i in range(0,1713):

  Temp_Img=image.load_img('/content/drive/My Drive/colab_data/test_images/' + str(i) + '.jpeg', target_size = (32,32),grayscale=True)
  Temp_Img=image.img_to_array(Temp_Img)
  X_test.append(Temp_Img)

/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/utils.py:98: UserWarning: grayscale is deprecated. Please use color_mode = "grayscale"
  warnings.warn('grayscale is deprecated. Please use '


In [0]:
X_test=np.array(X_test)
#print(X_test)
#type(X_test)

In [0]:
print (X_test.shape)

(1713, 32, 32, 1)


In [0]:
X_train = []

for j in range(1714,8559):
  
  Train_img=image.load_img('/content/drive/My Drive/colab_data/train_images/' +str(j) + '.jpeg', target_size=(32,32),grayscale=True)
  Train_img=image.img_to_array(Train_img)
  X_train.append(Train_img)

/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/utils.py:98: UserWarning: grayscale is deprecated. Please use color_mode = "grayscale"
  warnings.warn('grayscale is deprecated. Please use '


In [0]:
X_train=np.array(X_train)

In [0]:
print(X_train.shape)

(6845, 32, 32, 1)


In [0]:
print(X_train.shape)

(6845, 32, 32, 3)


In [0]:
#def predict(self, X, batch_size=32, verbose=0, check_input_shapes=True):
   # if check_input_shapes:
#X = standardize_input_data(X, self.input_names,
         #                          self.internal_input_shapes,
         #                          check_batch_dim=False)
   # else:
     #   X = standardize_input_data(X, self.input_names,
                                  # check_batch_dim=False)

In [0]:
#X.shape
y.shape

(8560, 3, 2)

In [0]:
#X = X.reshape((8560, 32 * 32))
#X = X.astype('float32') / 255

In [0]:
#from sklearn.model_selection import train_test_split

#y_train, y_test = train_test_split(y, test_size=0.20, random_state=42)

[[[21 11]
  [10 13]
  [16 20]]

 [[25 13]
  [ 6 18]
  [20 28]]

 [[20 12]
  [10 13]
  [16 18]]

 ...

 [[22 13]
  [ 9 12]
  [16 18]]

 [[15  5]
  [10 20]
  [23 16]]

 [[21 13]
  [10 10]
  [17 20]]]


In [0]:
from keras.models import Model,save_model,load_model
from keras.layers import Input

In [0]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_44 (Conv2D)           (None, 32, 32, 300)       3000      
_________________________________________________________________
max_pooling2d_20 (MaxPooling (None, 16, 16, 300)       0         
_________________________________________________________________
conv2d_45 (Conv2D)           (None, 16, 16, 250)       675250    
_________________________________________________________________
max_pooling2d_21 (MaxPooling (None, 8, 8, 250)         0         
_________________________________________________________________
conv2d_46 (Conv2D)           (None, 8, 8, 200)         450200    
_________________________________________________________________
conv2d_47 (Conv2D)           (None, 8, 8, 150)         270150    
_________________________________________________________________
conv2d_48 (Conv2D)           (None, 8, 8, 100)         135100    
__________

In [0]:


Model.fit(X_train, y_train,
          batch_size=128,
          epochs=100,
          verbose=1,
          validation_data=(X_test, y_test))
         

AttributeError: ignored

In [0]:
!pip freeze  

absl-py==0.7.1
alabaster==0.7.12
albumentations==0.1.12
altair==3.0.1
astor==0.7.1
astropy==3.0.5
atari-py==0.1.7
atomicwrites==1.3.0
attrs==19.1.0
audioread==2.1.6
autograd==1.2
Babel==2.6.0
backcall==0.1.0
backports.tempfile==1.0
backports.weakref==1.0.post1
beautifulsoup4==4.6.3
bleach==3.1.0
bokeh==1.0.4
boto==2.49.0
boto3==1.9.140
botocore==1.12.140
Bottleneck==1.2.1
branca==0.3.1
bs4==0.0.1
bz2file==0.98
cachetools==3.1.0
certifi==2019.3.9
cffi==1.12.3
chainer==5.4.0
chardet==3.0.4
Click==7.0
cloudpickle==0.6.1
cmake==3.12.0
colorlover==0.3.0
community==1.0.0b1
contextlib2==0.5.5
convertdate==2.1.3
coverage==3.7.1
coveralls==0.5
crcmod==1.7
cufflinks==0.14.6
cvxopt==1.2.3
cvxpy==1.0.15
cycler==0.10.0
cymem==2.0.2
Cython==0.29.7
cytoolz==0.9.0.1
daft==0.0.4
dask==1.1.5
dataclasses==0.6
datascience==0.10.6
decorator==4.4.0
defusedxml==0.6.0
dill==0.2.9
distributed==1.25.3
Django==2.2.1
dlib==19.16.0
dm-sonnet==1.23
docopt==0.6.2
docutils==0.14
dopamine-rl==1.0.5
easydict==1.9
ecos=